import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import BlogPosts from '../components/BlogPosts'
import SubmitBlogPostForm from '../components/SubmitBlogPostForm'
import { ADD_BLOGPOST , DELETE_BLOGPOST, EDIT_BLOGPOST, GET_BLOGPOSTS} from '../graphql/queries'
import { useQuery, useMutation } from '@apollo/client'


export default function Home() {

  const [addBlogPost] = useMutation(ADD_BLOGPOST, {
    onCompleted: () => {
      refetch()
    }
  })

  const onSubmit = (e) => {
    e.preventDefault()
    addBlogPost({variables: {text: e.target.text.value}})
    e.target.text.value = "";
  }


  const [deleteBlogPost] = useMutation(DELETE_BLOGPOST, {
    onCompleted: () => {
      refetch()
    }
  })

  const onDelete = (id) => deleteBlogPost({variables: { id }})


  const [editBlogPost] = useMutation(EDIT_BLOGPOST)

  const onEdit =  (e) => {
    e.preventDefault()
    editBlogPost({variables: {id: e.target.id, text: e.target.editName.value}})
  }


  const { loading, error, data, refetch } = useQuery(GET_BLOGPOSTS)   

  if(loading) {
      return "loading"
  }
  if(error){
      return "error"
  }


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SubmitBlogPostForm onSubmit={onSubmit}></SubmitBlogPostForm>
      <BlogPosts data={data} onDelete={onDelete} onEdit={onEdit}></BlogPosts>
     
    </div>
  )
}
